/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import java.util.LinkedList;

/**
 *
 * @author drako9
 */
public class MyMap extends javax.swing.JPanel {

    /**
     * Creates new form MyMap
     */
    private LinkedList< City > cities;
    private LinkedList< Country > countries;
    public MyMap() {
        initComponents();
        setSize( 500, 500 );
        cities = new LinkedList< City >();
        cities.add( new City( 10, 10, "A1", 4000000 ) );
        cities.add( new City( 10, 30, "A2", 2000000 ) );
        cities.add( new City( 30, 30, "A3", 2000000 ) );
        cities.add( new City( 30, 10, "A4", 2000000 ) );
        
        cities.add( new City( 50, 10, "B1", 4000000 ) );
        cities.add( new City( 50, 30, "B2", 2000000 ) );
        cities.add( new City( 70, 30, "B3", 2000000 ) );
        cities.add( new City( 70, 10, "B4", 2000000 ) );
        
        
        cities.add( new City( 100, 100, "C1", 4000000 ) );
        cities.add( new City( 100, 120, "C2", 2000000 ) );
        cities.add( new City( 120, 120, "C3", 2000000 ) );
        cities.add( new City( 120, 100, "C4", 2000000 ) );
        
        cities.add( new City( 150, 150, "D1", 4000000 ) );
        cities.add( new City( 150, 170, "D2", 2000000 ) );
        cities.add( new City( 170, 170, "D3", 2000000 ) );
        cities.add( new City( 170, 150, "D4", 2000000 ) );
        
        /*
        countries = new LinkedList<Country>();
        for(int i = 1 ; i <= 4 ; ++i)
        {
            countries.add(new Country(new LinkedList<>(cities.subList((i-1)*4,i*4-1)),cities.get(i*4-1)));
        }*/
    }
    
    public void paint( java.awt.Graphics g ) {
        super.paint( g );
        for(int i = 0 ; i < cities.size() ; ++i)
        {
            cities.get(i).draw(g);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
